# Welcome to Jekyll!
#

# Site settings
title: The Engineer Experience
description: Engineering Management Consultancy 
owner: Dec0de Me # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: hello@dec0de-me.co.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.the-engineer-experience.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
social:
  twitter: https://twitter.com/dec0de_me_
  linkedin-square: https://www.linkedin.com/company/the-engineer-experience/
  #github: https://github.com/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:



# Build settings
markdown: kramdown
#sass:
#  style: compressed
